export const FETCH_ESPECIES_PENDING = "FETCH_ESPECIES_PENDING";
export const FETCH_ESPECIES_SUCCESS = "FETCH_ESPECIES_SUCCESS";
export const FETCH_ESPECIES_ERROR = "FETCH_ESPECIES_ERROR";

export const FETCH_ARVORES_PENDING = "FETCH_ARVORES_PENDING";
export const FETCH_ARVORES_SUCCESS = "FETCH_ARVORES_SUCCESS";
export const FETCH_ARVORES_ERROR = "FETCH_ARVORES_ERROR";

export const FETCH_GRUPOS_PENDING = "FETCH_GRUPOS_PENDING";
export const FETCH_GRUPOS_SUCCESS = "FETCH_GRUPOS_SUCCESS";
export const FETCH_GRUPOS_ERROR = "FETCH_GRUPOS_ERROR";

export const FETCH_COLHEITAS_PENDING = "FETCH_COLHEITAS_PENDING";
export const FETCH_COLHEITAS_SUCCESS = "FETCH_COLHEITAS_SUCCESS";
export const FETCH_COLHEITAS_ERROR = "FETCH_COLHEITAS_ERROR";

export const SAVE_ESPECIE_PENDING = "SAVE_ESPECIE_PENDING";
export const SAVE_ESPECIE_SUCCESS = "SAVE_ESPECIE_SUCCESS";
export const SAVE_ESPECIE_ERROR = "SAVE_ESPECIE_ERROR";

export const SAVE_ARVORE_PENDING = "SAVE_ARVORE_PENDING";
export const SAVE_ARVORE_SUCCESS = "SAVE_ARVORE_SUCCESS";
export const SAVE_ARVORE_ERROR = "SAVE_ARVORE_ERROR";

export const SAVE_GRUPO_PENDING = "SAVE_GRUPO_PENDING";
export const SAVE_GRUPO_SUCCESS = "SAVE_GRUPO_SUCCESS";
export const SAVE_GRUPO_ERROR = "SAVE_GRUPO_ERROR";

export const SAVE_COLHEITA_PENDING = "SAVE_COLHEITA_PENDING";
export const SAVE_COLHEITA_SUCCESS = "SAVE_COLHEITA_SUCCESS";
export const SAVE_COLHEITA_ERROR = "SAVE_COLHEITA_ERROR";
