// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const Moment = require("moment");

const uniqueValue = Moment().format();
const todaySlash = Moment().format("DD/MM/YYYY");
const todayDash = Moment().format("YYYY-MM-DD");

const waitFor = async (milis) =>
  new Promise((resolve) => setTimeout(resolve, milis));

describe("add", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("add new especie", async function () {
    await driver.get("http://localhost:3001/");
    await driver.manage().window().setRect(1323, 741);
    await driver.findElement(By.css(".quarter:nth-child(1) svg")).click();
    await driver
      .findElement(By.id("form_in_modal_descricao"))
      .sendKeys("teste especie " + uniqueValue);
    await driver.findElement(By.css(".ant-btn-primary")).click();
    await waitFor(1000);
    assert(
      (await driver
        .findElement(
          By.css(".quarter:nth-child(1) .content .ant-card:last-child")
        )
        .getText()) ==
        "teste especie " + uniqueValue
    );
  });
  it("add new arvore", async function () {
    await driver.get("http://localhost:3001/");
    await driver.manage().window().setRect(1323, 741);
    await driver
      .findElement(By.css(".quarter:nth-child(2) .ant-card-head svg"))
      .click();
    await driver
      .findElement(By.id("form_in_modal_descricao"))
      .sendKeys("teste arvore " + uniqueValue);
    await driver.findElement(By.id("form_in_modal_idade")).click();
    await driver.findElement(By.id("form_in_modal_idade")).sendKeys("1");
    await driver.findElement(By.id("form_in_modal_especie")).click();
    await driver
      .findElement(By.id("form_in_modal_especie"))
      .sendKeys(Key.ENTER);
    await driver.findElement(By.css(".ant-btn-primary")).click();
    await waitFor(1000);
    assert(
      (await driver
        .findElement(
          By.css(".quarter:nth-child(2) .content .ant-card:last-child")
        )
        .getText()) ==
        "teste arvore " + uniqueValue + " - 1 ano"
    );
  });
  it("add new grupo", async function () {
    await driver.get("http://localhost:3001/");
    await driver.manage().window().setRect(1323, 741);
    await driver
      .findElement(By.css(".quarter:nth-child(3) .ant-card-head svg"))
      .click();
    await driver
      .findElement(By.id("form_in_modal_nome"))
      .sendKeys("teste grupo " + uniqueValue);
    await driver
      .findElement(By.id("form_in_modal_descricao"))
      .sendKeys("descricao");
    await driver
      .findElement(By.id("form_in_modal_arvores"))
      .sendKeys(Key.ENTER);
    await driver
      .findElement(By.css(".ant-select-item-option:nth-child(1)"))
      .click();
    await driver.findElement(By.css('label[title="Árvores"]')).click();
    await driver.findElement(By.css(".ant-btn-primary")).click();
    await waitFor(1000);
    assert(
      (await driver
        .findElement(
          By.css(".quarter:nth-child(3) .content .ant-card:last-child")
        )
        .getText()) ==
        "teste grupo " + uniqueValue + " - descricao"
    );
  });
  it("add new colheita of arvore", async function () {
    await driver.get("http://localhost:3001/");
    await driver.manage().window().setRect(1323, 741);
    await driver
      .findElement(By.css(".quarter:nth-child(4) .ant-card-head svg"))
      .click();
    await driver
      .findElement(By.id("form_in_modal_informacoes"))
      .sendKeys("teste colheita arvore " + uniqueValue);
    await driver
      .findElement(By.id("form_in_modal_data"))
      .sendKeys(todayDash + Key.ENTER);
    await driver.findElement(By.id("form_in_modal_pesoBruto")).click();
    await driver.findElement(By.id("form_in_modal_pesoBruto")).sendKeys("1");
    await driver.findElement(By.id("form_in_modal_isGroup")).click();
    await driver
      .findElement(By.css(".ant-select-item-option:nth-child(2)"))
      .click();
    await driver.findElement(By.id("form_in_modal_refArvore")).click();
    await driver
      .findElement(By.id("form_in_modal_refArvore"))
      .sendKeys(Key.ENTER);
    await driver.findElement(By.css(".ant-btn-primary")).click();
    await waitFor(1000);
    assert(
      (await driver
        .findElement(
          By.css(".quarter:nth-child(4) .content .ant-card:last-child")
        )
        .getText()) ==
        "teste colheita arvore " + uniqueValue + " - " + todaySlash + " - 1Kg"
    );
  });
  it("add new colheita of grupo", async function () {
    await driver.get("http://localhost:3001/");
    await driver.manage().window().setRect(1323, 741);
    await driver
      .findElement(By.css(".quarter:nth-child(4) .ant-card-head svg"))
      .click();
    await driver
      .findElement(By.id("form_in_modal_informacoes"))
      .sendKeys("teste colheita grupo " + uniqueValue);
    await driver
      .findElement(By.id("form_in_modal_data"))
      .sendKeys(todayDash + Key.ENTER);
    await driver.findElement(By.id("form_in_modal_pesoBruto")).click();
    await driver.findElement(By.id("form_in_modal_pesoBruto")).sendKeys("1");
    await driver.findElement(By.id("form_in_modal_isGroup")).click();
    await driver
      .findElement(By.css(".ant-select-item-option:nth-child(1)"))
      .click();
    await driver.findElement(By.id("form_in_modal_refGrupo")).click();
    await driver
      .findElement(By.id("form_in_modal_refGrupo"))
      .sendKeys(Key.ENTER);
    await driver.findElement(By.css(".ant-btn-primary")).click();
    await waitFor(1000);
    assert(
      (await driver
        .findElement(
          By.css(".quarter:nth-child(4) .content .ant-card:last-child")
        )
        .getText()) ==
        "teste colheita grupo " + uniqueValue + " - " + todaySlash + " - 1Kg"
    );
  });
});
